


```{r}
library(Seurat)
library(scCustomize)
library(SeuratData)
library(SeuratWrappers)
library(Azimuth)
library(BPCells)
library(dplyr)
library(ggplot2)
library(cowplot)
library(patchwork)
options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
```


```{r}
cortex.E11_5.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635072_E11_5_filtered_gene_bc_matrices_h5.h5"))
cortex.E11_5 <- CreateSeuratObject(counts = cortex.E11_5.counts)

cortex.E12_5.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635073_E12_5_filtered_gene_bc_matrices_h5.h5"))
cortex.E12_5 <- CreateSeuratObject(counts = cortex.E12_5.counts)

cortex.E13_5.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635074_E13_5_filtered_gene_bc_matrices_h5.h5"))
cortex.E13_5 <- CreateSeuratObject(counts = cortex.E13_5.counts)

cortex.E14_5.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635075_E14_5_filtered_gene_bc_matrices_h5.h5"))
cortex.E14_5 <- CreateSeuratObject(counts = cortex.E14_5.counts)

cortex.E15_5_S1.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635076_E15_5_S1_filtered_gene_bc_matrices_h5.h5"))
cortex.E15_5_S1 <- CreateSeuratObject(counts = cortex.E15_5_S1.counts)

cortex.E16.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635077_E16_filtered_gene_bc_matrices_h5.h5"))
cortex.E16 <- CreateSeuratObject(counts = cortex.E16.counts)

cortex.E18_5_S1.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635078_E18_5_S1_filtered_gene_bc_matrices_h5.h5"))
cortex.E18_5_S1 <- CreateSeuratObject(counts = cortex.E18_5_S1.counts)

cortex.E18_S3.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635079_E18_S3_filtered_gene_bc_matrices_h5.h5"))
cortex.E18_S3 <- CreateSeuratObject(counts = cortex.E18_S3.counts)

cortex.P1_S1.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635080_P1_S1_filtered_gene_bc_matrices_h5.h5"))
cortex.P1_S1 <- CreateSeuratObject(counts = cortex.P1_S1.counts)

cortex.P1_S2.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM4635081_P1_S2_filtered_gene_bc_matrices_h5.h5"))
cortex.P1_S2 <- CreateSeuratObject(counts = cortex.P1_S2.counts)

cortex.E10_v1.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM5277843_E10_v1_filtered_feature_bc_matrix.h5"))
cortex.E10_v1 <- CreateSeuratObject(counts = cortex.E10_v1.counts)

cortex.E17_5.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM5277844_E17_5_filtered_feature_bc_matrix.h5"))
cortex.E17_5 <- CreateSeuratObject(counts = cortex.E17_5.counts)

cortex.P4.counts <- Read10X_h5(filename = here::here("data/GSE153164_RAW/GSM5277845_P4_filtered_feature_bc_matrix.h5"))
cortex.P4 <- CreateSeuratObject(counts = cortex.P4.counts)
# class(cortex[["RNA"]])
```

```{r}
# Create a vector with the stage of development for each object
stage_info <- c("E11.5", "E12.5", "E13.5", "E14.5", "E15.5", "E16", "E18.5", "E18", "P1", "P1", "E10", "E17.5", "P4")

# Merge the Seurat objects
merged_cortex <- merge(
  x = cortex.E11_5,
  y = c(cortex.E12_5, cortex.E13_5, cortex.E14_5, cortex.E15_5_S1, cortex.E16, cortex.E18_5_S1, cortex.E18_S3, cortex.P1_S1, cortex.P1_S2, cortex.E10_v1, cortex.E17_5, cortex.P4),
  add.cell.ids = stage_info,
  project = "Cortex_Development"
)

# Add the stage information as metadata
merged_cortex$stage <- factor(sapply(strsplit(colnames(merged_cortex), split = "_"), `[`, 1))

# Print the metadata column
head(merged_cortex@meta.data)
```


```{r}
# rejoin layers
merged_cortex[["RNA"]] <- JoinLayers(merged_cortex[["RNA"]])
Layers(merged_cortex[["RNA"]])

# Split layers
merged_cortex[["RNA"]] <- split(merged_cortex[["RNA"]], f = merged_cortex$stage)
Layers(merged_cortex[["RNA"]])

# Find variable features
merged_cortex <- FindVariableFeatures(merged_cortex, verbose = FALSE)
merged_cortex <- NormalizeData(merged_cortex, verbose = FALSE)
# Scale data
merged_cortex <- ScaleData(merged_cortex, verbose = FALSE)

# Run PCA
merged_cortex <- RunPCA(merged_cortex, verbose = FALSE)
```

```{r}
# Azimuth::RunAzimuth(merged_cortex, reference = "mousecortexref")
# RunAzimuth(merged_cortex, reference = here::here("data/Azimuth/"), timeout = 10L, homolog.table = here::here("/data/references/homologs.rds"))
```

```{r}
# Integrate layers using CCA
merged_cortex <- IntegrateLayers(
  object = merged_cortex, method = CCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = FALSE
)

# Find neighbors
merged_cortex <- FindNeighbors(merged_cortex, reduction = "integrated.cca", dims = 1:30)

# Find clusters
merged_cortex <- FindClusters(merged_cortex, resolution = 2, cluster.name = "cca_clusters")

# Run UMAP
merged_cortex <- RunUMAP(merged_cortex, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")

# Integrate layers using Harmony
merged_cortex <- IntegrateLayers(
  object = merged_cortex, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = FALSE
)

# Find neighbors
merged_cortex <- FindNeighbors(merged_cortex, reduction = "harmony", dims = 1:30)

# Find clusters
merged_cortex <- FindClusters(merged_cortex, resolution = 2, cluster.name = "harmony_clusters")

# Run UMAP
merged_cortex <- RunUMAP(merged_cortex, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
```


```{r}
# Create DimPlot
p1 <- DimPlot(
  merged_cortex,
  reduction = "umap.harmony",
  group.by = c("stage", "harmony_clusters"),
  combine = FALSE, label.size = 2
)

p2 <- DimPlot(
  merged_cortex,
  reduction = "umap.cca",
  group.by = c("stage", "cca_clusters"),
  combine = FALSE, label.size = 2
)
```

```{r, fig.height=18, fig.width=20}
wrap_plots(c(p1, p2), ncol = 2, byrow = F)
```

```{r}
SeuratDisk::SaveH5Seurat(merged_cortex, here::here("data/"))
```


```{r, fig.height=3.55555556, fig.width=48}
genes.embed <- c(
  "Abcd1",
  "Abcd2",
  "Abcd3",
  "Acaa1",
  "Acaa2",
  "Acox1",
  "Agrn",
  "Agt",
  "Alcam",
  "Aldh1a1",
  "Aldh1l1",
  "Aldoc",
  "Angpt1",
  "Apoe",
  "App",
  "Aqp4",
  "Arf1",
  "Bmp7",
  "Bsg",
  "Caf4",
  "Ccl25",
  "Ckb",
  "Cnr1",
  "Cnr2",
  "Col4a5",
  "Cst3",
  "Dagla",
  "Daglb",
  "Decr2",
  "Dcc",
  "Dnm1",
  "Drp1",
  "Ech1",
  "Efna5",
  "Egfr",
  "Enho",
  "Eno1",
  "Faah",
  "Fgf1",
  "Fgfr3",
  "Fis1",
  "Fos",
  "Fth1",
  "Ftl1",
  "Gfap",
  "Gja1",
  "Gli1",
  "Glul",
  "Gnai2",
  "Gnas",
  "H2-K1",
  "Hacd2",
  "Hadhb",
  "Hbegf",
  "Hepacam",
  "Hif1",
  "Htra1",
  "Igsf1",
  "Il18",
  "Il1rapl1",
  "Itgav",
  "Jam2",
  "Lama2",
  "Lamb2",
  "Lcat",
  "Lgi1",
  "Lgi4",
  "Lpcat3",
  "Lrpap1",
  "Lrrc4b",
  "Lxn",
  "Mdk",
  "Mdv1",
  "Mfn1",
  "Mfn2",
  "Mgll",
  "Mief1",
  "Napepld",
  "Ncam1",
  "Ncan",
  "Ndrg2",
  "Nfasc",
  "Nfia",
  "Nlgn3",
  "Nrxn1",
  "Nrxn2",
  "Ntn1",
  "Ntrk3",
  "Opa1",
  "Otp",
  "Pex1",
  "Pex10",
  "Pex12",
  "Pex13",
  "Pex14",
  "Pex16",
  "Pex2",
  "Pex26",
  "Pex3",
  "Pex6",
  "Pkm",
  "Pla2g7",
  "Plcb1",
  "Psap",
  "Ptn",
  "Pygb",
  "Ralyl",
  "Rgma",
  "Rtn4",
  "S100a1",
  "S100a6",
  "S100b",
  "Siah1a",
  "Siah1b",
  "Scd2",
  "Sdc2",
  "Sema6a",
  "Sema6d",
  "Sgcd",
  "Sirpa",
  "Slc1a2",
  "Slc1a3",
  "Slc38a1",
  "Slc4a4",
  "Slc6a11",
  "Slc7a10",
  "Slit1",
  "Slit2",
  "Slitrk2",
  "Sorbs1",
  "Sox9",
  "Sparc",
  "Spon1",
  "Tafa1",
  "Timp3",
  "Tkt",
  "Trpv1",
  "Vcam1",
  "Vegfa"
)
merged_cortex <-
  Store_Palette_Seurat(
    seurat_object = merged_cortex,
    palette = rev(brewer.pal(n = 11, name = "Spectral")),
    palette_name = "expr_Colour_Pal"
  )
FeaturePlot_scCustom(
    merged_cortex,
    colors_use = merged_cortex@misc$expr_Colour_Pal,
    features = genes.embed[genes.embed %in%
                               rownames(merged_cortex)],
    max.cutoff = "q99",
    na_color = "lightgray",
    figure_plot = T,
    pt.size = 1,
    reduction = "umap.harmony",
    split.by = "stage",
    split_collect = FALSE,
    label = F,
    label_feature_yaxis = TRUE,
    combine = FALSE
)
```
```{r, fig.height=72, fig.width=48}
# Get the list of S100 family genes
s100_genes <- grep("^S100", rownames(merged_cortex), value = TRUE)

# Create a custom FeaturePlot for each S100 gene
plot_list <-
    lapply(
        c(s100_genes, "Cacybp", "Siah1a", "Siah1b"),
        function(gene) {
            FeaturePlot_scCustom(
                seurat_object = merged_cortex,
                features = gene,
                colors_use = merged_cortex@misc$expr_Colour_Pal,,
                na_color = "lightgray",
                order = TRUE,
                pt.size = 1,
                reduction = "umap.harmony",
                split.by = "stage",
                split_collect = FALSE,
                label = F,
                label_feature_yaxis = TRUE,
                combine = FALSE
            )
        })

# Combine the plots into a single grid
combined_plot <- patchwork::wrap_plots(plot_list, ncol = 1)

# Display the combined plot
print(combined_plot)
```


```{r}
# Create a compact DotPlot
compact_plot <- DotPlot(
  object = merged_cortex,
  features = c(s100_genes,
               "Cacybp",
               "Siah1a",
               "Siah1b"),
  group.by = "stage",
  cluster.idents = FALSE,
  scale = TRUE,
  dot.scale = 6
) + RotatedAxis()

# Display the compact plot
print(compact_plot)
```


```{r}

```


```{r}
sessioninfo::session_info()
```

